### PR TITLE
Update Set-NPSCertificate to support multiple EAPs

### PR DESCRIPTION
**Pull request by amorrowbellarmine**
The original version of this function only supports PEAP MSCHAPv2.
This update supports for PEAP and EAP-TLS (smartcards/certificates).

### CODE REVIEW

**Comment by rmbolger** [comment]
Hey @amorrowbellarmine, thanks for the enhancement. This function was contributed originally by @pieter-lazzaro. Unfortunately, I don't have the expertise with NPS to really review it properly. But it looks like a relatively straightforward update. Hoping Pieter is still around just to verify it doesn't break his existing use-case before I merge it.

**Comment by amorrowbellarmine** [comment]
No problem. I was excited to see the module supported NPS, but quickly realized the function didn't work with our environment because we had both EAP-TLS (Microsoft calls it "Smart Card or other certificate") and PEAP MSCHAPv2 enabled for our wireless policies. This update makes the function iterate through all EAP configurations for the specified RADIUS profile.

A more through re-write of the function would allow the user to specify which EAP configuration they want to update since, technically, each one can be set to use a different certificate. That could be a future enhancement. In our case, we want to use the same certificate for both EAP configurations so the current code change works in our environment.

**Comment by pieter-lazzaro** [comment]
LGTM, I just did the bare minimum do get my use case working. Literally cobbled together blog posts until it worked. :) I don't have time to check these changes on my system but I can't see why it would cause any issues.

**Comment by rmbolger** [comment]
Good enough for me. I'll see if I can get an updated release out with this next week.

**Pull request merged**
