### PR TITLE
Add Set-ExchangeCertificate

### PR DESCRIPTION
**Pull request by nemchik**
Following up on https://github.com/rmbolger/Posh-ACME.Deploy/issues/2

I have not yet had the facilities to test this, but I figured it'd be good to have a single place to see the changes all together instead of me referring to individual commits in the issue.

What we have here SHOULD be a working solution, but confirmation via testing is needed.

### CODE REVIEW

**Comment by rmbolger** [comment]
No worries on the delay. I'm in no rush.

**Comment by nemchik** [comment]
Just reviewing all my open PRs. This code is still valid, but with office 365 being used more and more I have yet to have the opportunity to confirm that all the pieces work together in this context.

I don't see that trend reversing anytime soon, so unless someone else is able to test and provide feedback this may be dead in the water unfortunately.

**Comment by n3cr0cr0w** [comment]
I'd like this to be added, tested with Exchange 2019.

**Comment by rmbolger** [comment]
Hooray! Thanks for testing, @n3cr0cr0w. Merging now.

**Comment by nemchik** [comment]
@n3cr0cr0w you're a true hero! I wrote this right after most of my clients switched to o365 and never had a chance to test it. Glad it worked for you!

**Pull request merged**
